### ISSUE TITLE
ERROR: tcpserver  tcpserver 39373 : error reading message: End of file 

### ISSUE THREAD

**Issue by layssi** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#11]
The TCP server is causing this error on reset.
I believe it is happening on "control_client.disconnect()".

**Comment by praveen-palanisamy** [comment]
Hi @layssi 
That usually happens at the end of an episode when the server is in the process of starting a new episode. In my experience, it is harmless and the environment should start serving the next episode soon after that and the agent should be able to proceed.

**Comment by praveen-palanisamy** [comment]
Closing this as it is a warning message from a dependency that is okay to ignore.
