### ISSUE TITLE
Gatthering observations and actions in CARLA

### ISSUE THREAD

**Issue by AliBaheri** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#12]
Collecting samples in Open AI gym is fairly straightforward. But what is the best way to collect observations and actions in the complex environment such as CARLA including all driving scenarios such as `straight, turn, navigation, and dynamic navigation`. 

I guess it would be beneficial to add some info/code snippet in the Wiki or repository as this is the first step of many RL algorithms.

**Comment by AliBaheri** [comment]
Hi Praveen,
Can you please give some tips in this regard?

**Comment by praveen-palanisamy** [comment]
Hi @AliBaheri : Sorry for the delayed response. I just could get to this.

If you are still looking for gathering observations and actions in CARLA, the quickest way is to use [the existing "dataset"](https://drive.google.com/file/d/1hloAeyamYn-H6MfV1dRtY1gJPhkR55sY/view) made available through [CARLA](https://github.com/carla-simulator/imitation-learning) which already has several hours of driving through such scenarios that you mention.

If you want to collect the data yourself, you can use the method described in [this wiki page](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/wiki/create-carla-scenarios) to create the scenarios you want and then manually drive through them using keyboard control or joystick (example: Logitech) control. 

Hope that helps.

**Comment by githubce** [comment]
Author provided the solution. Reopen if you want to continue discussion.
