### ISSUE TITLE
question in the carla_env.py

### ISSUE THREAD

**Issue by fangchuan** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#18]
well, today I 'm engaged to reviewing and debugging the implementation of gym compatible environment-carlar_env.py, and I have found several bugs.

First, it's not necessary to define the `GROUND_Z` , which was mainly used to delivered to Planner instance. In fact, i think it is not advisable to use GROUND_Z, because different game map has different z value, we cannot just fix the ground z value of the vehicle.

Then, i was confused about this code snippet:
`    
elif self.config["enable_planner"]:
            distance_to_goal = self.planner.get_shortest_path_distance(
                [current_measurement.transform.location.x, current_measurement.transform.location.y, 
                                                                                       current_measurement.transform.location.z],
                [current_measurement.transform.orientation.x, current_measurement.transform.orientation.y, 
                                                                                           current_measurement.transform.orientation.z],
                [self.end_pos.location.x, self.end_pos.location.y, self.end_pos.location.z],
                [self.end_pos.orientation.x, self.end_pos.orientation.y, self.end_pos.orientation.z]) / 100
`
while you calculate the distance to destination by deviding 100?
I do need your help, thanks a lot!

**Comment by praveen-palanisamy** [comment]
>First, it's not necessary to define the `GROUND_Z` , which was mainly used to delivered to Planner instance. In fact, i think it is not advisable to use GROUND_Z, because different game map has different z value, we cannot just fix the ground z value of the vehicle.

Carla is a 3D driving environment. So, the use of the `Z` coordinate is very much advisable in my opinion. To your second point of using a fixed `Z` coordinate: Yes. Each map has it's own elevation profile. As mentioned in the code comment just above the `GROUND_Z` declaration, for 2D navigation, we can assume that the ground is flat. This is the case with the Carla maps available in the stable releases. The value of `GROUND_Z` was obtained directly from those maps. The code is compatible with all Carla *stable* releases. 

Regarding the distance calculation:
In the stable Carla releases, the measurement units were in centimeters and so I divided the values by 100 to get the result in meters.

**Comment by praveen-palanisamy** [comment]
Hope that answers your questions. If it does, please feel free to close the issue.
