### ISSUE TITLE
How to do inference for Carla after training on OpenAI gym using Ray?

### ISSUE THREAD

**Issue by Deepak3994** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#22]
Hi,

I have trained for A3C algorithm on Carla using Gym environment. May i know like at what point of time the models get dumped and also how to do the inference on the same for Carla.

**Comment by praveen-palanisamy** [comment]
Hi @Deepak3994 :

Models are automatically saved as the performance (best_reward attained) improves. You can change how frequently an improved model is saved by adjusting this config param:

https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/8a334e0d11e12654ddf1418f54738e8338137c9e/ch8/async_a2c_parameters.json#L13

If you are using the [asyn_a2c_agent.py](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/async_a2c_agent.py) script, you can use the `--test` command-line argument to "do the inference".
