### ISSUE TITLE
A2C agent doesn't act

### ISSUE THREAD

**Issue by Amakri1020** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#24]
Hi, 

For some reason when I try to run the trained a2c agent in CARLA it doesn't take any actions, just sits there doing nothing. These are my terminal outputs:

(rl_gym_book) amakri@amakri-Zephyrus-M-GM501GS:~/Hands-On-Intelligent-Agents-with-OpenAI-Gym-master/ch8$ python a2c_agent.py --env Carla-v0 --gpu-id 0
Loaded Advantage Actor-Critic model state from trained_models/A2C_Carla-v0.ptm  which fetched a best mean reward of: -0.08981079755592294  and an all time best reward of: 1.0340544147491457
Initializing new Carla server...
Error connecting: (localhost:56639) failed to connect: [Errno 111] Connection refused, attempt 0
Start pos 36 ([0.0, 3.0]), end 40 ([0.0, 3.0])
Starting new episode...
actor0:Episode#:0 	 ep_reward:5.085380562726176e-10 	 mean_ep_rew:5.085380562726176e-10	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 56641 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:1 	 ep_reward:1.574227504116339e-09 	 mean_ep_rew:1.0413827801944784e-09	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 56641 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:2 	 ep_reward:1.461007756921785e-20 	 mean_ep_rew:6.94255186801189e-10	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 56641 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:3 	 ep_reward:-1.8116123954554487e-19 	 mean_ep_rew:5.206913900556014e-10	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 56641 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...
actor0:Episode#:4 	 ep_reward:8.738404666586943e-10 	 mean_ep_rew:5.9132120537622e-10	 best_ep_reward:1.0340544147491457
ERROR: tcpserver 56641 : error reading message: End of file 
Start pos 36 ([0.0, 2.0]), end 40 ([-1.0, 2.0])
Starting new episode...

Any ideas on why this is happening?

**Comment by LocLePhuoc** [comment]
I encountered the same problem.

**Comment by praveen-palanisamy** [comment]
>`Loaded Advantage Actor-Critic model state from trained_models/A2C_Carla-v0.ptm which fetched a best mean reward of: -0.08981079755592294`

You will probably have to train the agent for more episodes. 

The mean reward of ` -0.08981079755592294` signifies that the agent hasn't learned much. It's likely that, the the trained agent "brain"/model, has learned only to stay put to avoid collisions or something so that's why it's probably staying still.

**Comment by Amakri1020** [comment]
That's true, but it is still loading the trained A2C_Carla-v0.ptm agent for the train mode correct? It has the same behaviour in test mode unfortunately =\ it simply sits there not taking any actions.

**Comment by praveen-palanisamy** [comment]
In that case, the agent needs to be trained more.

If you are observing the same behavior for several episodes, its very likely that the trained agent "brain"/model seems to have learnt only so much (to stay still to avoid collisions).
________________________________

**Comment by praveen-palanisamy** [comment]
But, it is strange if you don't see the vehicle moving at all. It is supposed to be trying several actions and each will produce different trajectories of motion good or bad.
