### ISSUE TITLE
Problem with CARLA and Gym

### ISSUE THREAD

**Issue by AliBaheri** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#3]
Hi,
Thanks for great work!

I have successfully installed CARLA (0.8.2) on Ubuntu 18 and able to see the car in the environment when I run:

`~/software/CARLA_0.8.2/CarlaUE4.sh`

However, we I run this command:

`~/HOIAWOG/ch7$ python carla-gym/carla_gym/envs/carla_env.py`

I will face with the following message:

`Traceback (most recent call last):
  File "/home/baheri/HOIAWOG/ch7/carla-gym/carla_gym/envs/carla/transform.py", line 18, in <module>
    from . import carla_server_pb2 as carla_protocol
  File "/home/baheri/HOIAWOG/ch7/carla-gym/carla_gym/envs/carla/carla_server_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "carla-gym/carla_gym/envs/carla_env.py", line 32, in <module>
    from carla.client import CarlaClient
  File "/home/baheri/HOIAWOG/ch7/carla-gym/carla_gym/envs/carla/client.py", line 14, in <module>
    from . import sensor
  File "/home/baheri/HOIAWOG/ch7/carla-gym/carla_gym/envs/carla/sensor.py", line 19, in <module>
    from .transform import Transform, Translation, Rotation, Scale
  File "/home/baheri/HOIAWOG/ch7/carla-gym/carla_gym/envs/carla/transform.py", line 20, in <module>
    raise RuntimeError('cannot import "carla_server_pb2.py", run '
RuntimeError: cannot import "carla_server_pb2.py", run the protobuf compiler to generate this file`

**Not sure what happen...It seems that the code is not able to connect with the client.**

Any help appreciated.

**Comment by praveen-palanisamy** [comment]
Hi Ali,

> ImportError: No module named 'google'

As per the Traceback you posted, it looks like you do not have the `protobuf` python package installed.

If you are using conda environment, you can install it using this command: `conda install protobuf` if not, you can use this command: `pip install protobuf`

Hope that helps.

**Comment by praveen-palanisamy** [comment]
To make it easier to install all the dependencies needed for running all the agents in this repository including the CARLA Python dependencies, you can use the [conda_env.yaml](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/conda_env.yaml) file in the root of this repository. 
This command : `conda env create -f conda_env.yaml -n "HOIAWOG"` will create a conda environment named `HOIAWOG` which will have all the necessary python packages and correct versions needed.

**Comment by AliBaheri** [comment]
Thanks now it works perfect.
