### ISSUE TITLE
brew install boost-python --with-python3 does not work anymore

### ISSUE THREAD

**Issue by DerekGrant** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#30]
In chapter 3
Instructions for macOS
- brew install boost-python --with-python3
has been changed to
- brew install boost-python3
[stackoverflow](https://github.com/Homebrew/homebrew-core/issues/24369)

**Comment by praveen-palanisamy** [comment]
@DerekGrant, thanks for posting the stale command in the book's text and the correction/fix for it! I appreciate it :clap: .
I am going to start tagging such issues together to later update the text in a revised version of the book if I get a chance to revise.

**Comment by DerekGrant** [comment]
/fix
thanks a lot! I am going through the codes and try to collect the changes.
