### ISSUE TITLE
does carla_gym env work on windows?

### ISSUE THREAD

**Issue by PhanindraParashar** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#33]

**Comment by praveen-palanisamy** [comment]
If you have the CARLA server running on Windows and the necessary Python packages in a virtual env, `carla_gym` should work on Windows.

**Comment by praveen-palanisamy** [comment]
Closing this issue since your question was answered. Please re-open if you run into any issues after running.
