### ISSUE TITLE
ch7 error during reset

### ISSUE THREAD

**Issue by Panshark** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#34]
When I run `python carla-gym/carla_gym/envs/carla_env.py`

I always have this error:

```
Initializing new Carla server...
Start pos 36 ([0.0, 3.0]), end 40 ([0.0, 3.0])
Starting new episode...
Error during reset: Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch7/carla-gym/carla_gym/envs/carla/client.py", line 174, in _read_sensor_data
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch7/carla-gym/carla_gym/envs/carla_env.py", line 223, in reset
    return self.reset_env()
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch7/carla-gym/carla_gym/envs/carla_env.py", line 290, in reset_env
    image, py_measurements = self._read_observation()
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch7/carla-gym/carla_gym/envs/carla_env.py", line 397, in _read_observation
    measurements, sensor_data = self.client.read_data()
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch7/carla-gym/carla_gym/envs/carla/client.py", line 127, in read_data
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/Hands-On-Intelligent-Agents-with-OpenAI-Gym/ch7/carla-gym/carla_gym/envs/carla/client.py", line 127, in <genexpr>
    return pb_message, dict(x for x in self._read_sensor_data())
RuntimeError: generator raised StopIteration

Clearing Carla server state
ERROR:Initializing new Carla server...
```

Do you know how to fix it? Really thanks a lot.

**Comment by praveen-palanisamy** [comment]
Hi @Panshark ,
Thank you for posting with the error log. This message in the error log: `ERROR:Initializing new Carla server...` indicates that the CARLA server failed to initialize. 
1. Have you made sure `CARLA_SERVER` environment variable is pointing to the CARLA server binary on your machine?
2. Which version of CARLA server are you using? The code was tested with CARLA 0.8.x and is expected to work with newer version until CARLA 0.9.6

**Comment by Panshark** [comment]
> Hi @Panshark , Thank you for posting with the error log. This message in the error log: `ERROR:Initializing new Carla server...` indicates that the CARLA server failed to initialize.
> 
> 1. Have you made sure `CARLA_SERVER` environment variable is pointing to the CARLA server binary on your machine?
> 2. Which version of CARLA server are you using? The code was tested with CARLA 0.8.x and is expected to work with newer version until CARLA 0.9.6

I fixed it by modifying line 174 in client.py
```
def _read_sensor_data(self):
        while True:
            data = self._stream_client.read()
            if not data:
                # error fixed
                # raise StopIteration
                return
            yield self._parse_sensor_data(data)
```
But I don't know if this will cause new problems, at least for now it seems to be working  well.

**Comment by praveen-palanisamy** [comment]
@Panshark : Glad that you got it working. It does sound like the `data` from the CARLA client was `None` only at the start/first-few reads in your case so, your change looks fine to me. 
Closing this issue for now. Feel free to re-open if you run into issues again.
