### ISSUE TITLE
How to replace self._spec = lambda: None

### ISSUE THREAD

**Issue by Panshark** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#35]
Hi @praveen-palanisamy ,

I am trying to use multiprocessing on carla_env in ch8, but I found this error

```
File "/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CarlaEnv.__init__.<locals>.Data'
```

I think it might be because carla_env class use lambda in its __init__ method.

I tried to use:

```
def _spec():
     return 0
```

or

```
class NS(object): 
           pass
        self._spec = NS()
```

they all failed, I guess that pickle functions can't work in python. Can you give me some ideas on how to fix this problem? What should I replace this lambda:None?

**Comment by praveen-palanisamy** [comment]
Hi @Panshark !
Could you please post the full error log or the trace to see the call stack when you run into this error?

On your other note, (just some pointers) lambda functions can be pickled if that's what you meant to ask. While a custom handler method may be required depending on the lambda, you _could_ simply use the `dill` python package or replace `pickle` with `dill` like this: `import dill as pickle`.

**Comment by Panshark** [comment]
Hi @praveen-palanisamy ,

I think dill could not work, but I find `import multiprocess as mp` can solve this problem.

**Comment by praveen-palanisamy** [comment]
Glad that you got it working and the issue is resolved! Thank you for posting what worked for you.
The [multiprocess](https://github.com/uqfoundation/multiprocess) package uses [dill](https://github.com/uqfoundation/dill) under the hood to serialize all the objects that pickle fails to serialize.
