### ISSUE TITLE
Change weather during the training

### ISSUE THREAD

**Issue by Panshark** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#38]
Hi @praveen-palanisamy ,

In my training environment, I want to change the weather during the training. For instance, rain in the first 50 steps and sunshine in the last 50 steps. But I have no idea what to do, could do you help me?

Thank you very much.

**Comment by praveen-palanisamy** [comment]
Hi @Panshark , please use the [MACAD-Gym](https://github.com/praveen-palanisamy/macad-gym) package for customizing the weather conditions during training. 

Using [MACAD-Gym[(https://github.com/praveen-palanisamy/macad-gym) you can configure the weather using the following mapping:

```python
#: Weather mapping
WEATHERS = {
    0: carla.WeatherParameters.ClearNoon,
    1: carla.WeatherParameters.CloudyNoon,
    2: carla.WeatherParameters.WetNoon,
    3: carla.WeatherParameters.WetCloudyNoon,
    4: carla.WeatherParameters.MidRainyNoon,
    5: carla.WeatherParameters.HardRainNoon,
    6: carla.WeatherParameters.SoftRainNoon,
    7: carla.WeatherParameters.ClearSunset,
    8: carla.WeatherParameters.CloudySunset,
    9: carla.WeatherParameters.WetSunset,
    10: carla.WeatherParameters.WetCloudySunset,
    11: carla.WeatherParameters.MidRainSunset,
    12: carla.WeatherParameters.HardRainSunset,
    13: carla.WeatherParameters.SoftRainSunset,
}
```
and a custom training scenario configuration that includes array values for the `weather_distribution` field:

`"weather_distribution": [4, 7], # Rain and sunshine`

**Comment by praveen-palanisamy** [comment]
Closing this issue. Feel free to [start a discussion](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/discussions) if you have follow-up questions.
