### ISSUE TITLE
DDPG CARLA action space (Ch 8)

### ISSUE THREAD

**Issue by AliBaheri** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#5]
Hi!
Thanks for your great work.

I wanted to collect data (i.e., a vast range of observations and a vast range of actions) in CARLA to test an algorithm. There are two options:

**Option 1:** Use a human recorded data. For example, use the following link where people have gathered a good data-set in CARLA here: 

[https://github.com/carla-simulator/imitation-learning](url)

In their data-set each observation comes with 28 **keys**:

1. Steer, float 
2. Gas, float
3. Brake, float 
4. Hand Brake, boolean 
5. Reverse Gear, boolean
6. Steer Noise, float 
7. Gas Noise, float 
8. Brake Noise, float
9. Position X, float 
10. Position Y, float 
11. Speed, float 
12. Collision Other, float 
13. Collision Pedestrian, float 
14. Collision Car, float 
15. Opposite Lane Inter, float 
16. Sidewalk Intersect, float 
17. Acceleration X,float 
18. Acceleration Y, float 
19. Acceleration Z, float 
20. Platform time, float 
21. Game Time, float 
22. Orientation X, float 
23. Orientation Y, float 
24. Orientation Z, float 
25. High level command, int ( 2 Follow lane, 3 Left, 4 Right, 5 Straight) 
26. Noise, Boolean ( If the noise, perturbation, is activated, (Not Used) ) 
27. Camera (Which camera was used) 
28. Angle (The yaw angle for this camera)

My immediate question is which of these considered in example in **Ch8** in DDPG algorithm? What was the action space in **Ch8**? I do not think you have considered **all possible 9 actions** in that code?

**Option 2**: We can also collect data by random policy...but it is important for me to have a diverse range of observations and actions? How can I do that in `carla_gym`? Because that starting and ending position prevents me to collect a diverse range of observations and actions. Dose the code only consider `throttle`, `steer`, and `break`? Could you please clarify this point?

King regards,

**Comment by AliBaheri** [comment]
Update: It seems that `Gas, float` and `Brake, float` has been concentrated in a single vector. So, in addition to `steer, float` totally there are only 2 actions in CARLA. Now, can I use the data point from the link above to construct my action data?

**Comment by praveen-palanisamy** [comment]
Glad that you figured it out. 

Yes. In Chapter 8, the agents  (A3C, A2C) use a continuous valued action space comprising of the steering, gas/throttle and brake values which correspond to items 1, 2 and 3 in the annotated CARLA dataset you mentioned above under option 1. Note that, the action space used is Box(2) and the gas and brake commands are combined into one float value in the range [-1, 1]. [-1,0) for brake levels and (0, 1] for gas/throttle levels. That is why there are only 2 actions. This was done to make it little bit easier for the agents to learn to drive.

I have updated the Chapter 7's README file [here](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/tree/master/ch7#2-carla-gym) to describe the state and action spaces.

Yes. You can definitely use the demonstrations in the dataset listed above.

If you want to collect your own samples but automatically, you can use the [a2c_agent](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/a2c_agent.py), or the [async_a2c_agent.py](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/async_a2c_agent.py) or any other rollout policy.  This will give you variety in the rollouts especially when the policy is stochastic. You may find the `--test` argument option to the above scripts useful and you can add your code to modify the test routine to also log/record the samples.

You can modify the start/end locations as well as the routes using the [scenarios.json file](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/environment/carla_gym/envs/scenarios.json)

Hope that helps.

**Comment by AliBaheri** [comment]
> If you want to collect your own samples but automatically, you can use the [a2c_agent](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/a2c_agent.py), or the [async_a2c_agent.py](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/async_a2c_agent.py) or any other rollout policy. This will give you variety in the rollouts especially when the policy is stochastic. You may find the `--test` argument option to the above scripts useful and you can add your code to modify the test routine to also log/record the samples.

Hi Praveen,
I have a question here. Basically my goal here is to collect some observations and actions to test an algorithm. It turns out that the performance is not good when I use the human recorded data. So I am interested to collect some sample by the policy learned from A2C/A3C (as you suggested in your post). Can you please give more details how can I generate those samples using that?
Thanks.

**Comment by praveen-palanisamy** [comment]
I just realized that this is quite related to #12 . You already list: Option 1 (existing dataset), Option 2 ( using a random/trained agent to collect demonstrations) and we discussed about Option 3 (manual driving) in #12. I think these are all the options I can think of to collect demonstrations.

>It turns out that the performance is not good when I use the human recorded data

I am not sure why this is the case with your specific use case. Generally, human demonstrations are as best as you can get for a baseline (unless you already have a trained agent that is super-human).

**Comment by githubce** [comment]
Author provided the solution. Reopen if you want to continue discussion.
