### ISSUE TITLE
Transfer a policy to CARLA

### ISSUE THREAD

**Issue by AliBaheri** [PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym#7]
Hi @praveen-palanisamy, thanks for doing great work.

I have a policy from an RL algorithm in `.pk` format and I want to see if the car drives well or not on CARLA. Do you know how can I do that or refer me to a good tutorial for this purpose?

`test_agent_proc.start()`
`test_agent_proc.join()`

Thanks.

**Comment by praveen-palanisamy** [comment]
I assume that you are referring to the trained policy weights stored in a (pickle ?) file. If you have the policy graph definitions, you can create a new policy object and load the weights from this saved policy file and then run the agent in "test" mode (rollouts without training/updating the policy) similar to the `--test` mode in [train_a2c.py](https://github.com/PacktPublishing/Hands-On-Intelligent-Agents-with-OpenAI-Gym/blob/master/ch8/a2c_agent.py) script in this repo.
